# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32ae4e993fb7046aa0e3f9825d53bcb2beb218339560572ce73daa29104ab7cb18c61a805493c6ef9db8e960c6a2710fac462b4884479480aed9506f640de5fc

test:
  secret_key_base: 697c95a9999e0b9e957d2395d42dc498bb75c774e0270390f1c1dc0d63fad58701e1824b20285aaa38f69643fbf8fbf6b1145cb5653ce7acc0d6b0ccd5c3f430

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
